-- MySQL Script generated by MySQL Workbench and Annotated manually
-- This script drops the existing database and regenerates it from scratch.

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NEXT
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `NEXT`;
CREATE SCHEMA IF NOT EXISTS `NEXT` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `NEXT` ;

CREATE TABLE usuario (
  id_usuario INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  correo VARCHAR(100) UNIQUE,
  contraseña VARCHAR(100) NOT NULL,
  salt VARCHAR(45) NOT NULL,
  estado BOOLEAN DEFAULT TRUE,
  fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rol (
  id_rol INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE
);

INSERT INTO rol (nombre) VALUES
('PASAJERO'),
('CONDUCTOR'),
('ADMIN');

CREATE TABLE usuario_rol (
  id_usuario INT NOT NULL,
  id_rol INT NOT NULL,
  PRIMARY KEY (id_usuario, id_rol),
  FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
  FOREIGN KEY (id_rol) REFERENCES rol(id_rol)
);

CREATE TABLE conductor (
  id_usuario INT PRIMARY KEY,
  licencia VARCHAR(50) NOT NULL,
  estado BOOLEAN DEFAULT FALSE,
  fecha_aprobacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE paradero (
  id_paradero INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL UNIQUE,
  distrito VARCHAR(60) DEFAULT NULL,
  direccion VARCHAR(255) DEFAULT NULL,
  longitud DOUBLE DEFAULT NULL,
  latitud DOUBLE DEFAULT NULL,
  estado BOOLEAN DEFAULT TRUE
);

CREATE TABLE ruta (
  id_ruta INT AUTO_INCREMENT PRIMARY KEY,
  origen INT NOT NULL,
  destino INT NOT NULL,
  tiempo DOUBLE NOT NULL,
  distancia DOUBLE NOT NULL,
  estado BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (origen) REFERENCES paradero(id_paradero),
  FOREIGN KEY (destino) REFERENCES paradero(id_paradero)
);

CREATE TABLE solicitud (
  id_solicitud INT AUTO_INCREMENT PRIMARY KEY,
  id_usuario INT NOT NULL,
  origen INT NOT NULL,
  destino INT NOT NULL,
  precio_estimado DOUBLE NOT NULL,
  distancia DOUBLE NOT NULL,
  tiempo_estimado DOUBLE NOT NULL,
  estado TINYINT NOT NULL,
  fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
  FOREIGN KEY (origen) REFERENCES paradero(id_paradero),
  FOREIGN KEY (destino) REFERENCES paradero(id_paradero)
);

-- NECESSARY CHANGE: Added 'estado' and made conductor nullable/username
CREATE TABLE viaje (
  id_viaje INT AUTO_INCREMENT PRIMARY KEY,
  conductor VARCHAR(80), 
  id_usuario INT NOT NULL,
  origen INT NOT NULL,
  destino INT NOT NULL,
  fecha TIMESTAMP NOT NULL,
  precio DOUBLE NOT NULL,
  duracion INT NOT NULL,
  distancia DOUBLE NOT NULL,
  estado VARCHAR(20) DEFAULT 'PENDIENTE',
  FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
  FOREIGN KEY (origen) REFERENCES paradero(id_paradero),
  FOREIGN KEY (destino) REFERENCES paradero(id_paradero)
);

CREATE TABLE historial_busqueda (
  id_historial INT AUTO_INCREMENT PRIMARY KEY,
  id_usuario INT,
  origen INT,
  destino INT,
  fecha TIMESTAMP NOT NULL,
  FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
  FOREIGN KEY (origen) REFERENCES paradero(id_paradero),
  FOREIGN KEY (destino) REFERENCES paradero(id_paradero)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;