-- MySQL Script generated by MySQL Workbench and Annotated manually
-- This script drops the existing database and regenerates it from scratch.

-- Save the current state of UNIQUE_CHECKS to a variable and disable them
-- This allows us to insert data without checking for uniqueness constraints immediately
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

-- Save the current state of FOREIGN_KEY_CHECKS to a variable and disable them
-- This prevents errors when dropping tables that have relationships
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

-- Save the current SQL_MODE and set a strict mode for the session
-- This ensures strict data validation (no invalid dates, no division by zero, etc.)
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema travelplus
-- -----------------------------------------------------

-- Drop the schema 'travelplus' if it exists to clean the environment
-- This fulfills the requirement to "drop everything and regenerate"
DROP SCHEMA IF EXISTS `travelplus`;

-- Create the schema 'travelplus' if it doesn't exist (it won't, because we just dropped it)
-- We set the default character set to utf8mb4 for full Unicode support
CREATE SCHEMA IF NOT EXISTS `travelplus` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;

-- Select the 'travelplus' database for all subsequent operations
USE `travelplus` ;

-- -----------------------------------------------------
-- Table `travelplus`.`usuario`
-- -----------------------------------------------------

-- Create the 'usuario' table to store standard user (client) information
CREATE TABLE IF NOT EXISTS `travelplus`.`usuario` (
  -- Primary Key: Unique ID for the user, auto-increments
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  -- The user's full real name, cannot be null
  `nombre` VARCHAR(80) NOT NULL,
  -- The user's username, cannot be null and must be unique typically
  `nombre_usuario` VARCHAR(50) NOT NULL,
  -- The user's email address, can be null initially
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  -- The user's password, can be null initially
  `contraseña` VARCHAR(100) NULL DEFAULT NULL,
  -- Account status: TRUE for active, FALSE for blocked/inactive. Defaults to TRUE (active).
  `estado` BOOLEAN NOT NULL DEFAULT TRUE,
  -- The date the user registered. Stored as a BIGINT Unix timestamp (milliseconds).
  `fecha_registro` BIGINT NOT NULL DEFAULT 0,
  -- REMOVED: `tipo` ENUM field. Roles are now separated by table.
  
  -- Set the primary key constraint on id_usuario
  PRIMARY KEY (`id_usuario`),
  -- Create a unique index on 'correo' so no two users can have the same email
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  -- Create a unique index on 'nombre_usuario' so usernames are unique
  UNIQUE INDEX `nombre_usuario` (`nombre_usuario` ASC) VISIBLE)
-- Use the InnoDB storage engine for transaction support
ENGINE = InnoDB
-- Set the character set for the table
DEFAULT CHARACTER SET = utf8mb4
-- Set the collation for text comparison
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`administrador`
-- -----------------------------------------------------

-- Create the 'administrador' table to store admin credentials separately
CREATE TABLE IF NOT EXISTS `travelplus`.`administrador` (
  -- Primary Key: Unique ID for the admin
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  -- The admin's full name
  `nombre` VARCHAR(80) NOT NULL,
  -- The admin's email address, must be unique
  `correo` VARCHAR(100) NOT NULL,
  -- The admin's password
  `contraseña` VARCHAR(100) NOT NULL,
  -- Admin status: TRUE for active, FALSE for disabled. Defaults to TRUE.
  `estado` BOOLEAN NOT NULL DEFAULT TRUE,
  
  -- Set the primary key
  PRIMARY KEY (`id_administrador`),
  -- Ensure admin emails are unique
  UNIQUE INDEX `correo_admin` (`correo` ASC) VISIBLE)
-- Use the InnoDB storage engine
ENGINE = InnoDB
-- Set default character set
DEFAULT CHARACTER SET = utf8mb4
-- Set collation
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`amigo`
-- -----------------------------------------------------

-- Create the 'amigo' table to represent friendships between users
CREATE TABLE IF NOT EXISTS `travelplus`.`amigo` (
  -- The ID of the user adding the friend
  `id_usuario` INT NOT NULL,
  -- The ID of the friend being added
  `id_amigo` INT NOT NULL,
  -- Composite Primary Key: The combination of both IDs must be unique
  PRIMARY KEY (`id_usuario`, `id_amigo`),
  -- Index on id_amigo to speed up lookups by friend
  INDEX `id_amigo` (`id_amigo` ASC) VISIBLE,
  -- Foreign Key Constraint 1: Links 'id_usuario' to the 'usuario' table
  CONSTRAINT `amigo_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `travelplus`.`usuario` (`id_usuario`),
  -- Foreign Key Constraint 2: Links 'id_amigo' to the 'usuario' table
  CONSTRAINT `amigo_ibfk_2`
    FOREIGN KEY (`id_amigo`)
    REFERENCES `travelplus`.`usuario` (`id_usuario`))
-- Use the InnoDB storage engine
ENGINE = InnoDB
-- Set default character set
DEFAULT CHARACTER SET = utf8mb4
-- Set collation
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`paradero`
-- -----------------------------------------------------

-- Create the 'paradero' table to store bus stop/location data
CREATE TABLE IF NOT EXISTS `travelplus`.`paradero` (
  -- Primary Key: Unique ID for the bus stop
  `id_paradero` INT NOT NULL AUTO_INCREMENT,
  -- Name of the stop, cannot be null
  `nombre` VARCHAR(80) NOT NULL,
  -- District where the stop is located
  `distrito` VARCHAR(60) NULL DEFAULT NULL,
  -- Full address of the stop. VARCHAR(255) ensures it won't be truncated.
  `dirección` VARCHAR(255) NULL DEFAULT NULL,
  -- Geographical latitude of the stop
  `latitud` DOUBLE NULL DEFAULT NULL,
  -- Geographical longitude of the stop
  `longitud` DOUBLE NULL DEFAULT NULL,
  -- Set the primary key
  PRIMARY KEY (`id_paradero`),
  -- Ensure the name of the stop is unique across the database
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
-- Use the InnoDB storage engine
ENGINE = InnoDB
-- Set default character set
DEFAULT CHARACTER SET = utf8mb4
-- Set collation
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`ruta`
-- -----------------------------------------------------

-- Create the 'ruta' table to define routes between two paraderos
CREATE TABLE IF NOT EXISTS `travelplus`.`ruta` (
  -- Primary Key: Unique ID for the route
  `id_ruta` INT NOT NULL AUTO_INCREMENT,
  -- Foreign Key ID for the starting point (origin)
  `origen` INT NOT NULL,
  -- Foreign Key ID for the ending point (destination)
  `destino` INT NOT NULL,
  -- Estimated time for the route. Changed to INT (minutes) for consistency.
  `tiempo` INT NOT NULL,
  -- Distance of the route
  `distancia` DOUBLE NOT NULL,
  -- Status of the route: TRUE (active) / FALSE (blocked). Defaults to TRUE.
  `estado` BOOLEAN NOT NULL DEFAULT TRUE,
  -- Set the primary key
  PRIMARY KEY (`id_ruta`),
  -- Index for faster queries filtering by origin
  INDEX `origen` (`origen` ASC) VISIBLE,
  -- Index for faster queries filtering by destination
  INDEX `destino` (`destino` ASC) VISIBLE,
  -- Foreign Key Constraint: Links 'origen' to 'paradero' table
  CONSTRAINT `ruta_ibfk_1`
    FOREIGN KEY (`origen`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`),
  -- Foreign Key Constraint: Links 'destino' to 'paradero' table
  CONSTRAINT `ruta_ibfk_2`
    FOREIGN KEY (`destino`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`))
-- Use the InnoDB storage engine
ENGINE = InnoDB
-- Set default character set
DEFAULT CHARACTER SET = utf8mb4
-- Set collation
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`estadistica_ruta`
-- -----------------------------------------------------

-- Create 'estadistica_ruta' to store analytics data about routes
CREATE TABLE IF NOT EXISTS `travelplus`.`estadistica_ruta` (
  -- The ID of the route this statistic belongs to
  `id_ruta` INT NOT NULL,
  -- A counter field (e.g., how many times used), defaults to 0
  `contador` INT NULL DEFAULT '0',
  -- Primary Key is the route ID itself (one stat record per route)
  PRIMARY KEY (`id_ruta`),
  -- Foreign Key Constraint: Links 'id_ruta' to the 'ruta' table
  CONSTRAINT `estadistica_ruta_ibfk_1`
    FOREIGN KEY (`id_ruta`)
    REFERENCES `travelplus`.`ruta` (`id_ruta`))
-- Use the InnoDB storage engine
ENGINE = InnoDB
-- Set default character set
DEFAULT CHARACTER SET = utf8mb4
-- Set collation
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`historial_busqueda`
-- -----------------------------------------------------

-- Create 'historial_busqueda' to log user searches
CREATE TABLE IF NOT EXISTS `travelplus`.`historial_busqueda` (
  -- Primary Key: Unique ID for the history record
  `id_historial` INT NOT NULL AUTO_INCREMENT,
  -- The user who performed the search
  `id_usuario` INT NULL DEFAULT NULL,
  -- The origin ID searched for
  `origen` INT NULL DEFAULT NULL,
  -- The destination ID searched for
  `destino` INT NULL DEFAULT NULL,
  -- When the search happened. Stored as BIGINT Unix timestamp (milliseconds).
  `fecha` BIGINT NOT NULL DEFAULT 0,
  -- Set the primary key
  PRIMARY KEY (`id_historial`),
  -- Indices for optimizing search history lookups
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `origen` (`origen` ASC) VISIBLE,
  INDEX `destino` (`destino` ASC) VISIBLE,
  -- Foreign Key: Links to 'usuario'
  CONSTRAINT `historial_busqueda_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `travelplus`.`usuario` (`id_usuario`),
  -- Foreign Key: Links origin to 'paradero'
  CONSTRAINT `historial_busqueda_ibfk_2`
    FOREIGN KEY (`origen`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`),
  -- Foreign Key: Links destination to 'paradero'
  CONSTRAINT `historial_busqueda_ibfk_3`
    FOREIGN KEY (`destino`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`))
-- Use the InnoDB storage engine
ENGINE = InnoDB
-- Set default character set
DEFAULT CHARACTER SET = utf8mb4
-- Set collation
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`viaje`
-- -----------------------------------------------------

-- Create 'viaje' table to store actual trips taken
CREATE TABLE IF NOT EXISTS `travelplus`.`viaje` (
  -- Primary Key: Unique ID for the trip
  `id_viaje` INT NOT NULL AUTO_INCREMENT,
  -- The user who took the trip
  `id_usuario` INT NOT NULL,
  -- The starting point of the trip
  `origen` INT NOT NULL,
  -- The destination of the trip
  `destino` INT NOT NULL,
  -- The date of the trip. Stored as BIGINT Unix timestamp (milliseconds).
  `fecha` BIGINT NOT NULL DEFAULT 0,
  -- The cost of the trip
  `precio` DOUBLE NOT NULL,
  -- The duration of the trip in minutes (INT).
  `duración` INT NOT NULL,
  -- The distance covered
  `distancia` DOUBLE NOT NULL,
  -- Set the primary key
  PRIMARY KEY (`id_viaje`),
  -- Indices for optimization
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `origen` (`origen` ASC) VISIBLE,
  INDEX `destino` (`destino` ASC) VISIBLE,
  -- Foreign Key: Links to 'usuario'
  CONSTRAINT `viaje_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `travelplus`.`usuario` (`id_usuario`),
  -- Foreign Key: Links to 'paradero' (origin)
  CONSTRAINT `viaje_ibfk_2`
    FOREIGN KEY (`origen`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`),
  -- Foreign Key: Links to 'paradero' (destination)
  CONSTRAINT `viaje_ibfk_3`
    FOREIGN KEY (`destino`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`))
-- Use the InnoDB storage engine
ENGINE = InnoDB
-- Set default character set
DEFAULT CHARACTER SET = utf8mb4
-- Set collation
COLLATE = utf8mb4_0900_ai_ci;


-- Restore the previous SQL_MODE
SET SQL_MODE=@OLD_SQL_MODE;
-- Restore the previous FOREIGN_KEY_CHECKS state
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- Restore the previous UNIQUE_CHECKS state
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;