-- MySQL Script generated by MySQL Workbench
-- Mon Dec  1 15:47:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema travelplus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema travelplus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travelplus` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `travelplus` ;

-- -----------------------------------------------------
-- Table `travelplus`.`amigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travelplus`.`amigo` (
  `id_usuario` INT NOT NULL,
  `id_amigo` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_amigo`),
  INDEX `id_amigo` (`id_amigo` ASC) VISIBLE,
  CONSTRAINT `amigo_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `travelplus`.`usuario` (`id_usuario`),
  CONSTRAINT `amigo_ibfk_2`
    FOREIGN KEY (`id_amigo`)
    REFERENCES `travelplus`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`estadistica_ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travelplus`.`estadistica_ruta` (
  `id_ruta` INT NOT NULL,
  `contador` INT NULL DEFAULT '0',
  PRIMARY KEY (`id_ruta`),
  CONSTRAINT `estadistica_ruta_ibfk_1`
    FOREIGN KEY (`id_ruta`)
    REFERENCES `travelplus`.`ruta` (`id_ruta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`historial_busqueda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travelplus`.`historial_busqueda` (
  `id_historial` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `origen` INT NULL DEFAULT NULL,
  `destino` INT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_historial`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `origen` (`origen` ASC) VISIBLE,
  INDEX `destino` (`destino` ASC) VISIBLE,
  CONSTRAINT `historial_busqueda_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `travelplus`.`usuario` (`id_usuario`),
  CONSTRAINT `historial_busqueda_ibfk_2`
    FOREIGN KEY (`origen`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`),
  CONSTRAINT `historial_busqueda_ibfk_3`
    FOREIGN KEY (`destino`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`paradero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travelplus`.`paradero` (
  `id_paradero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `distrito` VARCHAR(60) NULL DEFAULT NULL,
  `latitud` DOUBLE NULL DEFAULT NULL,
  `longitud` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_paradero`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travelplus`.`ruta` (
  `id_ruta` INT NOT NULL AUTO_INCREMENT,
  `origen` INT NOT NULL,
  `destino` INT NOT NULL,
  `tiempo` DOUBLE NOT NULL,
  `distancia` DOUBLE NOT NULL,
  `estado` ENUM('activa', 'bloqueada') NULL DEFAULT 'activa',
  PRIMARY KEY (`id_ruta`),
  INDEX `origen` (`origen` ASC) VISIBLE,
  INDEX `destino` (`destino` ASC) VISIBLE,
  CONSTRAINT `ruta_ibfk_1`
    FOREIGN KEY (`origen`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`),
  CONSTRAINT `ruta_ibfk_2`
    FOREIGN KEY (`destino`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travelplus`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `contraseña` VARCHAR(100) NULL DEFAULT NULL,
  `estado` ENUM('activo', 'bloqueado') NULL DEFAULT 'activo',
  `fecha_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo` ENUM('administrador', 'cliente') NOT NULL DEFAULT 'cliente',
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelplus`.`viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travelplus`.`viaje` (
  `id_viaje` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `origen` INT NOT NULL,
  `destino` INT NOT NULL,
  `fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `precio` DOUBLE NOT NULL,
  `duración` TIME NOT NULL,
  `distancia` DOUBLE NOT NULL,
  PRIMARY KEY (`id_viaje`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `origen` (`origen` ASC) VISIBLE,
  INDEX `destino` (`destino` ASC) VISIBLE,
  CONSTRAINT `viaje_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `travelplus`.`usuario` (`id_usuario`),
  CONSTRAINT `viaje_ibfk_2`
    FOREIGN KEY (`origen`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`),
  CONSTRAINT `viaje_ibfk_3`
    FOREIGN KEY (`destino`)
    REFERENCES `travelplus`.`paradero` (`id_paradero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
